In [1]:
import sqlite3
import numpy as np
import pandas as pd
import sqlite3

conn = sqlite3.connect('FPA_FOD_20170508.sqlite')
print("Connection Successful")
df = pd.read_sql("SELECT * from Fires",con=conn)
df

Connection Successful

,OBJECTID,FOD_ID,FPA_ID,SOURCE_SYSTEM_TYPE,SOURCE_SYSTEM,NWCG_REPORTING_AGENCY,NWCG_REPORTING_UNIT_ID,NWCG_REPORTING_UNIT_NAME,SOURCE_REPORTING_UNIT,SOURCE_REPORTING_UNIT_NAME,...,FIRE_SIZE_CLASS,LATITUDE,LONGITUDE,OWNER_CODE,OWNER_DESCR,STATE,COUNTY,FIPS_CODE,FIPS_NAME,Shape
0,1,1,FS-1418826,FED,FS-FIRESTAT,FS,USCAPNF,Plumas National Forest,0511,Plumas National Forest,...,A,40.036944,-121.005833,5.0,USFS,CA,63,063,Plumas,b'\x00\x01\xad\x10\x00\x00\xe8d\xc2\x92_@^\xc0...
1,2,2,FS-1418827,FED,FS-FIRESTAT,FS,USCAENF,Eldorado National Forest,0503,Eldorado National Forest,...,A,38.933056,-120.404444,5.0,USFS,CA,61,061,Placer,b'\x00\x01\xad\x10\x00\x00T\xb6\xeej\xe2\x19^\...
2,3,3,FS-1418835,FED,FS-FIRESTAT,FS,USCAENF,Eldorado National Forest,0503,Eldorado National Forest,...,A,38.984167,-120.735556,13.0,STATE OR PRIVATE,CA,17,017,El Dorado,b'\x00\x01\xad\x10\x00\x00\xd0\xa5\xa0W\x13/^\...
3,4,4,FS-1418845,FED,FS-FIRESTAT,FS,USCAENF,Eldorado National Forest,0503,Eldorado National Forest,...,A,38.559167,-119.913333,5.0,USFS,CA,3,003,Alpine,b'\x00\x01\xad\x10\x00\x00\x94\xac\xa3\rt\xfa]...
4,5,5,FS-1418847,FED,FS-FIRESTAT,FS,USCAENF,Eldorado National Forest,0503,Eldorado National Forest,...,A,38.559167,-119.933056,5.0,USFS,CA,3,003,Alpine,b'\x00\x01\xad\x10\x00\x00@\xe3\xaa.\xb7\xfb]\...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1880460,1880461,300348363,2015CAIRS29019636,NONFED,ST-CACDF,ST/C&L,USCASHU,Shasta-Trinity Unit,CASHU,Shasta-Trinity Unit,...,A,40.481637,-122.389375,13.0,STATE OR PRIVATE,CA,None,None,None,b'\x00\x01\xad\x10\x00\x00P\xb8\x1e\x85\xeb\x9...
1880461,1880462,300348373,2015CAIRS29217935,NONFED,ST-CACDF,ST/C&L,USCATCU,Tuolumne-Calaveras Unit,CATCU,Tuolumne-Calaveras Unit,...,A,37.617619,-120.938570,12.0,MUNICIPAL/LOCAL,CA,None,None,None,b'\x00\x01\xad\x10\x00\x00\x00\x80\xbe\x88\x11...
1880462,1880463,300348375,2015CAIRS28364460,NONFED,ST-CACDF,ST/C&L,USCATCU,Tuolumne-Calaveras Unit,CATCU,Tuolumne-Calaveras Unit,...,A,37.617619,-120.938570,12.0,MUNICIPAL/LOCAL,CA,None,None,None,b'\x00\x01\xad\x10\x00\x00\x00\x80\xbe\x88\x11...
1880463,1880464,300348377,2015CAIRS29218079,NONFED,ST-CACDF,ST/C&L,USCATCU,Tuolumne-Calaveras Unit,CATCU,Tuolumne-Calaveras Unit,...,B,37.672235,-120.898356,12.0,MUNICIPAL/LOCAL,CA,None,None,None,b'\x00\x01\xad\x10\x00\x00x\xba_\xaa~9^\xc0\xb...
1880464,1880465,300348399,2015CAIRS26733926,NONFED,ST-CACDF,ST/C&L,USCABDU,San Bernardino Unit,CABDU,CDF - San Bernardino Unit,...,A,34.263217,-116.830950,13.0,STATE OR PRIVATE,CA,None,None,None,b'\x00\x01\xad\x10\x00\x00\x1c\xa7\xe8H.5]\xc0...

In [2]:
df['DISCOVERY_DATE'] = pd.to_datetime(df['DISCOVERY_DATE'] - pd.Timestamp(0).to_julian_date(), unit='D')
df['CONT_DATE'] = pd.to_datetime(df['CONT_DATE'] - pd.Timestamp(0).to_julian_date(), unit='D')
# Changing the data format for the above columns

In [3]:
df_by_cause_year = df.groupby(['STAT_CAUSE_CODE', 'FIRE_YEAR'])
df_by_cause_year.describe()

                          OBJECTID                                          \
                             count          mean            std        min
STAT_CAUSE_CODE FIRE_YEAR
1.0             1992       12230.0  2.527910e+05  342504.392951    41876.0
                1993        7539.0  4.240679e+05  449688.236367    53304.0
                1994       16204.0  2.358077e+05  302449.731858    60902.0
                1995        8075.0  3.003203e+05  359926.970744    75459.0
                1996       12634.0  2.490339e+05  295577.084503    84740.0
...                            ...           ...            ...        ...
13.0            2011       13903.0  1.559030e+06  107173.541433  1459301.0
                2012        3735.0  1.665889e+06  112573.572264  1565795.0
                2013        4241.0  1.674975e+06   56003.546701  1642884.0
                2014        3701.0  1.779357e+06   32669.041548  1728635.0
                2015        6276.0  1.849430e+06   21966.087009  1792723.0

                                                                         \
                                  25%        50%         75%        max
STAT_CAUSE_CODE FIRE_YEAR
1.0             1992         46288.25    51044.0   233335.75  1429058.0
                1993         56756.50   219808.0   953007.50  1860064.0
                1994         66003.75    72185.5   230902.25  1431404.0
                1995         78970.50   187793.0   236916.50  1438690.0
                1996         89555.75    95187.5   231806.75  1440356.0
...                               ...        ...         ...        ...
13.0            2011       1506363.50  1512485.0  1516802.50  1880251.0
                2012       1582825.00  1616896.0  1635304.00  1880281.0
                2013       1652860.00  1655662.0  1678895.00  1880415.0
                2014       1786426.00  1787351.0  1788276.00  1880431.0
                2015       1853312.75  1854930.5  1856499.25  1880464.0

                            FOD_ID                ...   LONGITUDE             \
                             count          mean  ...         75%        max
STAT_CAUSE_CODE FIRE_YEAR                         ...
1.0             1992       12230.0  4.353398e+05  ... -110.590486 -68.066667
                1993        7539.0  1.837476e+06  ...  -83.816667 -67.199996
                1994       16204.0  4.359959e+05  ... -108.584000 -68.049500
                1995        8075.0  1.022692e+06  ... -107.720317 -67.499400
                1996       12634.0  6.526346e+05  ... -108.584000 -71.325000
...                            ...           ...  ...         ...        ...
13.0            2011       13903.0  2.057538e+08  ...  -77.897400 -65.264175
                2012        3735.0  2.243872e+08  ... -116.672385 -65.273611
                2013        4241.0  2.086902e+08  ...  -94.034040 -65.305833
                2014        3701.0  3.001269e+08  ... -112.090100 -65.402941
                2015        6276.0  3.002806e+08  ... -110.427425 -65.985000

                          OWNER_CODE                                        \
                               count       mean       std  min   25%   50%
STAT_CAUSE_CODE FIRE_YEAR
1.0             1992         12230.0   5.594031  3.807187  1.0   4.0   5.0
                1993          7539.0   6.650219  4.535562  1.0   4.0   5.0
                1994         16204.0   5.439891  3.655052  1.0   3.0   5.0
                1995          8075.0   5.486192  3.943922  1.0   2.0   5.0
                1996         12634.0   5.014010  3.637241  1.0   2.0   5.0
...                              ...        ...       ...  ...   ...   ...
13.0            2011         13903.0  13.082716  2.582725  1.0  14.0  14.0
                2012          3735.0  11.693976  3.493172  1.0   8.0  14.0
                2013          4241.0  12.140533  3.305736  0.0  11.0  14.0
                2014          3701.0  12.192380  3.174860  1.0  10.0  14.0
                2015          6276.0  11.835883  3.074713  1.0   8.0  14.0


                            75%   max
STAT_CAUSE_CODE FIRE_YEAR
1.0             1992        5.0  14.0
                1993        8.0  14.0
                1994        5.0  14.0
                1995        5.0  14.0
                1996        5.0  14.0
...                         ...   ...
13.0            2011       14.0  15.0
                2012       14.0  15.0
                2013       14.0  15.0
                2014       14.0  15.0
                2015       14.0  15.0

[312 rows x 64 columns]

In [4]:
df_by_cause_year = df.groupby(['STAT_CAUSE_CODE', 'FIRE_YEAR']).apply(lambda x: x.sample(frac=0.2)).reset_index(drop = True)
df_by_cause_year['STAT_CAUSE_CODE'].value_counts()

5.0     85807
9.0     64763
7.0     56290
1.0     55695
13.0    33345
2.0     29525
4.0     15225
8.0     12232
3.0     10575
6.0      6693
11.0     2892
10.0     2300
12.0      759
Name: STAT_CAUSE_CODE, dtype: int64

In [5]:
df_by_cause_year['FIRE_YEAR'].value_counts()

2006    22801
2000    19282
2007    19116
2011    18112
1999    17873
2005    17723
2001    17317
2008    17077
2010    15978
2009    15664
1994    15192
2002    15130
1996    15115
2015    14898
2012    14555
1995    14294
2004    13855
1998    13674
2003    13653
1992    13596
2014    13552
2013    12956
1993    12399
1997    12289
Name: FIRE_YEAR, dtype: int64

In [6]:
df_by_cause_year.duplicated().value_counts()

False    376101
dtype: int64

In [7]:
df_by_cause_year.columns

Index(['OBJECTID', 'FOD_ID', 'FPA_ID', 'SOURCE_SYSTEM_TYPE', 'SOURCE_SYSTEM',
       'NWCG_REPORTING_AGENCY', 'NWCG_REPORTING_UNIT_ID',
       'NWCG_REPORTING_UNIT_NAME', 'SOURCE_REPORTING_UNIT',
       'SOURCE_REPORTING_UNIT_NAME', 'LOCAL_FIRE_REPORT_ID',
       'LOCAL_INCIDENT_ID', 'FIRE_CODE', 'FIRE_NAME',
       'ICS_209_INCIDENT_NUMBER', 'ICS_209_NAME', 'MTBS_ID', 'MTBS_FIRE_NAME',
       'COMPLEX_NAME', 'FIRE_YEAR', 'DISCOVERY_DATE', 'DISCOVERY_DOY',
       'DISCOVERY_TIME', 'STAT_CAUSE_CODE', 'STAT_CAUSE_DESCR', 'CONT_DATE',
       'CONT_DOY', 'CONT_TIME', 'FIRE_SIZE', 'FIRE_SIZE_CLASS', 'LATITUDE',
       'LONGITUDE', 'OWNER_CODE', 'OWNER_DESCR', 'STATE', 'COUNTY',
       'FIPS_CODE', 'FIPS_NAME', 'Shape'],
      dtype='object')

In [8]:
drop_columns = ['OBJECTID','FPA_ID', 'SOURCE_SYSTEM_TYPE', 'SOURCE_SYSTEM',
       'NWCG_REPORTING_UNIT_ID',
       'NWCG_REPORTING_UNIT_NAME', 'SOURCE_REPORTING_UNIT',
       'LOCAL_FIRE_REPORT_ID',
       'LOCAL_INCIDENT_ID', 'FIRE_CODE', 
       'ICS_209_INCIDENT_NUMBER', 'ICS_209_NAME', 'MTBS_ID', 'MTBS_FIRE_NAME',
       'COMPLEX_NAME', 'DISCOVERY_DOY',       
       'CONT_DOY',  'OWNER_CODE',
       'FIPS_CODE', 'FIPS_NAME', 'Shape']
df_by_cause_year.drop(drop_columns, axis=1, inplace=True)

In [9]:
df_by_cause_year.columns

Index(['FOD_ID', 'NWCG_REPORTING_AGENCY', 'SOURCE_REPORTING_UNIT_NAME',
       'FIRE_NAME', 'FIRE_YEAR', 'DISCOVERY_DATE', 'DISCOVERY_TIME',
       'STAT_CAUSE_CODE', 'STAT_CAUSE_DESCR', 'CONT_DATE', 'CONT_TIME',
       'FIRE_SIZE', 'FIRE_SIZE_CLASS', 'LATITUDE', 'LONGITUDE', 'OWNER_DESCR',
       'STATE', 'COUNTY'],
      dtype='object')

In [10]:
df_by_cause_year.shape

(376101, 18)

In [11]:
df_by_cause_year.head()

,FOD_ID,NWCG_REPORTING_AGENCY,SOURCE_REPORTING_UNIT_NAME,FIRE_NAME,FIRE_YEAR,DISCOVERY_DATE,DISCOVERY_TIME,STAT_CAUSE_CODE,STAT_CAUSE_DESCR,CONT_DATE,CONT_TIME,FIRE_SIZE,FIRE_SIZE_CLASS,LATITUDE,LONGITUDE,OWNER_DESCR,STATE,COUNTY
0,215495,BLM,Phoenix District Office,WASHCANYON,1992,1992-07-18,1730,1.0,Lightning,1992-07-18,1900,1.0,B,35.000000,-114.000800,BLM,AZ,None
1,208755,BIA,San Carlos Agency,MIDDLE,1992,1992-06-04,1535,1.0,Lightning,1992-06-04,1830,1.0,B,33.483400,-109.584000,BIA,AZ,None
2,43255,FS,Lolo National Forest,None,1992,1992-06-28,0900,1.0,Lightning,1992-06-28,1700,0.1,A,47.258333,-114.851667,USFS,MT,None
3,49676,FS,Tahoe National Forest,RIDGE,1992,1992-10-03,0920,1.0,Lightning,1992-10-03,1416,0.1,A,39.446667,-120.823333,USFS,CA,None
4,52065,FS,Winema National Forest,None,1992,1992-07-30,1340,1.0,Lightning,1992-07-30,1700,0.1,A,42.971667,-121.951667,USFS,OR,None

In [21]:
df_by_cause_year.to_csv('sampled_dataset.csv', index= False)

In [22]:
#conn.close()